# SPDX-FileCopyrightText: Maximilian Huber
#
# SPDX-License-Identifier: BSD-3-Clause

name:                opOSSum-lib
version:             0.1.0.0
github:              "maxhbr/opOSSum-lib"
license:             BSD3
author:              "Maximillian Huber"
maintainer:          "gh@maxhbr.de"
copyright:           "Maximilian Huber"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maxhbr/opOSSum-lib#readme>

dependencies:
- aeson
- aeson-pretty
- base >= 4.7 && < 5
- bytestring
- containers
- cryptohash-md5
- file-embed
- filepath
- mtl
- text
- unordered-containers
- vector
- yaml
- process
- uuid
- random
- zlib
# spdx stuff:
- Cabal
- spdx
- spdx-document

library:
  source-dirs: src

executables:
  opOSSum-lib-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opOSSum-lib

tests:
  opOSSum-lib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opOSSum-lib
    - hspec
    - QuickCheck
