# SPDX-FileCopyrightText: Maximilian Huber
#
# SPDX-License-Identifier: BSD-3-Clause

resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/8.yaml

packages:
- .

extra-deps:
- git: https://github.com/maxhbr/spdx-document-hs
  commit: da3496dceedb36c615d3e02a5836c15811b02d35
