# SPDX-FileCopyrightText: Maximilian Huber
#
# SPDX-License-Identifier: BSD-3-Clause

resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/6.yaml

packages:
- .

extra-deps:
- git: https://github.com/maxhbr/spdx-tools-hs
  commit: 25e7877930485c549a7b665b0593e49396c5ab76
- git: https://github.com/maxhbr/packageurl-hs
  commit: 81d3701a1a630e529862d3c639a69e09848f7cf6
- git: https://github.com/phadej/spdx
  commit: ef1807e08299150e4b42dfb33e87e2982be8d49c

