# SPDX-FileCopyrightText: Maximilian Huber
#
# SPDX-License-Identifier: BSD-3-Clause

resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/9.yaml

packages:
- .

extra-deps:
- git: https://github.com/maxhbr/spdx-tools-hs
  commit: a0cfb19eeba10f59be2d5d7e3e6d36b0988d2d57
- git: https://github.com/maxhbr/packageurl-hs
  commit: 5d4de0e17311e033e90c89afc6249722b42ce5a1
- spdx-1.0.0.2@sha256:7dfac9b454ff2da0abb7560f0ffbe00ae442dd5cb76e8be469f77e6988a70fed,2008

