# SPDX-FileCopyrightText: Maximilian Huber
#
# SPDX-License-Identifier: BSD-3-Clause

resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/8.yaml

packages:
- .
